language: python

python:
  - "3.7"
env:
  global:
    - MOZ_HEADLESS=1
addons:
  firefox: latest
# command to install dependencies
install:
  - sudo apt-get update
  - pip install -r requirements.txt
  - export PATH=$PATH:$(pwd)
  - export PATH=$PATH:/usr/lib/chromium-browser/

# command to run the actual booking
script:
  - python YMCA_booking.py

# After successful test, run coverage and send data to Coverall
after_success:
  - ls -lah # list the files in the root dir # Used to check voerage file generation
  - coveralls -d ./.coverage # Ask coverall to send the coverage file generated to coverall
