language: python

python:
  - "3.7"
env:
  global:
    - MOZ_HEADLESS=1
addons:
  firefox: latest
# command to install dependencies
before_install:
  - sudo apt-get install xvfb
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.19.0/geckodriver-v0.19.0-linux64.tar.gz
install:
  - sudo tar -xzf geckodriver-v0.19.0-linux64.tar.gz -C /usr/bin
  - sudo chmod a+x /usr/bin/geckodriver
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 5 # give xvfb some time to start
  - pip install -r requirements.txt
  - export PATH=$PATH:$(pwd)

# command to run the actual booking
script:
  - python YMCA_booking.py

# After successful test, run coverage and send data to Coverall
after_success:
  - ls -lah # list the files in the root dir # Used to check voerage file generation
  - coveralls -d ./.coverage # Ask coverall to send the coverage file generated to coverall
